### ISSUE TITLE
Missing bin?

### ISSUE THREAD

**Issue by RobinClowers** [revskill10/now-dev-cli#2]
This is a great idea, I would love to use it, but after installing `now-dev-cli`, I can't run `now-dev`. I'm not very familiar with authoring npm packages, but don't you need to list the binary in the [package.json bin](https://docs.npmjs.com/files/package.json#bin) section?

**Comment by revskill10** [comment]
@RobinClowers Ah, you're right, the `bin` is missing.
In the mean time, you can add a `script` to `package.json` to execute `now-dev` ?
Would you mind adding a PR for this ?

**Comment by RobinClowers** [comment]
Yeah, I was able to run it with a script. It took me a while to figure out what the deal was with the `next.config.js`, I have to say, it's pretty unexpected that it will overwrite your now.json file. I'm curious how you manage this, do you check in the generated now.json file alongside the now.config.js every time you change it? I would rather not have a generated file checked in, but I think you would have to for the now github integration to work...

**Comment by revskill10** [comment]
What i advice is , you shouldn't write `now.json` by hand, it should be generated from `now.config.js`.
It's my main idea here.
I'll stabilize this library soon, as soon as i touch it in production.
There're two advantages with `now.config.js`:
- You could programmatically build your `now.json` file anyway you want.
- You could require it from client-side code to have universal routing.
For live reloading , you could use `nodemon` ;)

**Comment by RobinClowers** [comment]
My point still stands, the now github integration requires a `now.json` file checked in to work, and it seems awkward to check in the generated file as well as the file that generates it. I think this project would fit into the ecosystem better if it consumed now.json, rather than requiring people to adopt your custom `now.config.js`. Of course, it's your project, so it's up to you. I'm not personally interested in adopting that format. Thanks for getting back to me though!

**Comment by revskill10** [comment]
Actually, first version of this library use native `now.json` format.
But there're some use cases that requires programmatically generation `now.json`, for example, to generate localized `now.json` based on some languages.
What's the point of github integration ? You always get a `now.json` after all to push to github.
This is just a pre-compiling step after development phase and before staging phase.
Secondly, the `now.config.js` is up to you, it just returns a json in Now V2 format.

**Comment by RobinClowers** [comment]
Perhaps I'm missing something? You said:

> You always get a now.json after all to push to github.

How does this happen? Are you using a git hook to generate it when you commit or push?

**Comment by RobinClowers** [comment]
The github integration deploys your application to now.sh every time you push: https://zeit.co/blog/workflow-improvements-now-github.

**Comment by revskill10** [comment]
It generates a `now.json` file with every restart of dev server (in `next-routes-middleware` package)

**Comment by revskill10** [comment]
There're two work-around for you in this cases:
- Provide an argument `now -A <your now.json> file` when deploying to Now
- Use the generated `now.json` file
I fixed the missing bin in the latest release. 
Hope to hear more suggestions from you.
